default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: sample_app_user
  password: my_password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test

production:
  <<: *default
  database: sample_app_production
  username: sample_app_user
  password: my_password
